language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
      secure: knP/DKO5OUrwDVOzSbWpTRsnEwV70jGHgOdSoMNxZDJLqCtjjQAj7458jMCtI+DWC9K1BzQMObmmPFNeNhopW95VEE7+zL82KlFcWttU6zgVD0gq7u8AiiTP/oqg6Psnawr/pEGSjJBtJ9fg80nZhpqx1o5BWUjLLpX5ZShnqzeTBwnMhGJ3tlA0swqOBEgChzkgofBukCLCl7218ovcA6WshyUdDOyI1qISgxzPtfrHyTjyYvHV9FcbDtvNLGK8/do/GGX/aL0GCerYQrj036aknOOhH2RdFA8ARdD4smj+0z5fXTksd/7Voi5oimt1H1rAoQ4aSzkzAbuudWcabyxvrsjda5RUoog66E5QxRbYjNU8aHe1+wL7ClFDMk2a5/wdEXn7YGGGw4uLAIlVYvdkxEafZu3dV6cEyVk9CsLEyUpQjHJ3NKqJEc+KJqh84aNfsSYdvaQBcPSckANX9RbGnhJ94rErJc1UgdV9IJMGx6UZBCuo49+Fd6UvIh0w9UKtyHtyOhPgrUkk9bo85fCvwrrhXtkCqyMEG6SnOLhXmMER11/NIMIHHp3aM+iZiXJqQKS23G0RQVIAo4tlwQIToN6Cu1H40lGrsfmQ1MwfbjXBWer91tiMV1rAlq80fUVw/SO6GlFJa17C9qyGjp6B21QW+sW4dzVLwMQmQVc=
  on:
    tags: true
    repo: Jackzzs/protacarve
    python: 3.8
